<?php

namespace App\Http\Requests\Admin\Wallet;

use App\Http\Requests\PaginationRequest;

class TransferListRequest extends PaginationRequest
{
    public function __construct(array $query = [], array $request = [], array $attributes = [], array $cookies = [], array $files = [], array $server = [], $content = null)
    {
        parent::__construct($query, $request, $attributes, $cookies, $files, $server, $content);
    }

    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    public function rules()
    {
        $settings = parent::rules(); // TODO: Change the autogenerated stub
        $settings['sender'] = 'sometimes';
//        $settings['date_from'] = 'sometimes|date:Y-m-d';
//        $settings['date_to'] = 'sometimes|date:Y-m-d';

        return $settings;
    }
}
