<?php

namespace App\Http\Requests\Admin\Stock;

use App\Http\Requests\PaginationRequest;

class SupplierListRequest extends PaginationRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    public function rules()
    {
        $settings = parent::rules(); // TODO: Change the autogenerated stub

        return $settings;
    }
}
